manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: your-git
      url-base: https://github.com/ikumoku

  projects:
    - name: zmk
      remote: zmkfirmware
      # 安定運用のため main ではなくタグ固定を推奨
      revision: v0.4
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: your-git
      revision: 72590a3

  self:
    path: config
